KAFKA_HOST: ${KF_HOST}
ZOOKEPER_HOST: ${ZKPR_HOST}
POSTGRES_USER: ${PG_USER}
POSTGRES_PASSWORD: ${PG_PASSWORD}
POSTGRES_URL: ${PG_URL}
#LOGSTASH_HOST: 3.64.251.107:5000

REALM: sweeft
KEYCLOAK_HOST: ${KC_HOST}
KEYCLOAK_ADMIN_USER: ${KC_ADMIN_USER}
KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
KEYCLOAK_CLIENT: ${KC_CLIENT}
KEYCLOAK_SECRET: ${KC_SECRET}
KEYCLOAK_INTERNAL_SERVICE_CLIENT_ID: sweeft-internal-service
KEYCLOAK_INTERNAL_SERVICE_CLIENT_SECRET: e3c2a56a-8411-4926-86cc-478467a7484a

REDIS_HOST: ${RDS_HOST}
ELASTIC_HOST: ${ES_HOST}
ELASTIC_URI: ${ES_URI}
ELASTIC_USERNAME: ${ES_USER}
ELASTIC_PASSWORD: ${ES_PASSWORD}
EUREKA_HOST: ${EURK_HOST}
SILKNET_SMS_URL: http://91.151.128.64:7777/pls/sms/phttp2sms.Process

LIMIT_HOST: https://appdev.keepz.me:9000
NEAR_LIMIT_EMAIL: likakhokhiashvili@gmail.com
SMS_PROVIDER_USERNAME: 995558900291
DISTRIBUTION_EMAIL: "rusamatkava@gmail.com, n.koberidze@keepz.me"
FAILED_ACQUIRING_EMAIL: likakhokhiashvili@gmail.com
NOTIFICATIONS_MAIL: dev.notifications@keepz.me
ALERTS_MAIL: dev.alerts@keepz.me
FAILED_REFUND_EMAIL: dev.alerts@keepz.me
CAMPAIGN_ALERT_EMAIL_FROM: keepzallerts@gmail.com
CAMPAIGN_ALERT_EMAIL: dev.notifications@keepz.me
DEVICE_DISCONNECTED_EMAIL: sandro.mekoshkishvili@makingscience.com
ALERT_FOREIGN_CURRENCY_DISTRIBUTION: lika.khokhiashvili@makingscience.com
GENERAL_ALERT: dev.alerts@keepz.me
ALERT_IBAN_REVIEW: dev.notifications@keepz.me
EXECUTE_SILKNET_HEALTH_CHECK: false
MONITOR_URL_CHECK_EXECUTE: true

spring:
  kafka:
    bootstrap-servers: ${KF_HOST}