AWS_ACC: ${AWS_ACCE}
AWS_SECRET: ${AWS_SEC}
AWS_REGION: ${AWS_REG}
AWS_ENDPOINT: ${AWS_END}
AWS_BUCKETNAME: ${AWS_S3}
AWS_FAKEMODE: false
AWS_ENDPOINT_DOC: ${AWS_END_DOC}
AWS_BUCKET_NAME_DOC: ${AWS_S3_DOC}
AWS_ACC_DOC: ${AWS_ACCE_DOC}
AWS_SECRET_DOC: ${AWS_SEC_DOC}

KAFKA_HOST: ${KF_HOST}
ZOOKEPER_HOST: ${ZKPR_HOST}


REALM: sweeft
KEYCLOAK_HOST: ${KC_HOST}
KEYCLOAK_ADMIN_USER: ${KC_ADMIN_USER}
KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
KEYCLOAK_CLIENT: ${KC_CLIENT}
KEYCLOAK_SECRET: ${KC_SECRET}
KEYCLOAK_INTERNAL_SERVICE_CLIENT_ID: sweeft-internal-service
KEYCLOAK_INTERNAL_SERVICE_CLIENT_SECRET: e3c2a56a-8411-4926-86cc-478467a7484a


EUREKA_HOST: ${EURK_HOST}

LIMIT_HOST: https://appdev.keepz.me:9000

IDENTOMAT_COMPANY_KEY: 6580b40d299edf612f00bf72_bf48a50e59ab4a065075485aaaf77dfb927daba2
IDENTOMAT_BASE_URL: https://widget.identomat.com/external-api/
IDENTOMAT_EXTERNAL_BASE_URL: https://external.api.identomat.com/

POSTGRES_USER: ${PG_USER}
POSTGRES_PASSWORD: ${PG_PASSWORD}
POSTGRES_URL: ${PG_URL}

spring:
  kafka:
    bootstrap-servers: ${KF_HOST}
  security:
    oauth2:
      client:
        registration:
          keycloak-service:
            client-id: ${KC_INTERNAL_SERVICE_CLIENT_ID}
            client-secret: ${KC_INTERNAL_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak-service:
            token-uri: ${KEYCLOAK_HOST}/auth/realms/${REALM}/protocol/openid-connect/token
