KAFKA_HOST: ${KF_HOST}
ZOOKEPER_HOST: ${ZKPR_HOST}
POSTGRES_USER: ${PG_USER}
POSTGRES_PASSWORD: ${PG_PASSWORD}
POSTGRES_URL: ${PG_URL}
FRAUD_ANALYZER_PORT: ${FA_PORT}
#LOGSTASH_HOST: 3.64.251.107:5000

REALM: sweeft
KEYCLOAK_HOST: ${KC_HOST}
KEYCLOAK_ADMIN_USER: ${KC_ADMIN_USER}
KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
KEYCLOAK_CLIENT: ${KC_CLIENT}
KEYCLOAK_SECRET: ${KC_SECRET}
KEYCLOAK_INTERNAL_SERVICE_CLIENT_ID: sweeft-internal-service
KEYCLOAK_INTERNAL_SERVICE_CLIENT_SECRET: e3c2a56a-8411-4926-86cc-478467a7484a

EUREKA_HOST: ${EURK_HOST}

REDIS_HOST: ${RDS_HOST}

spring:
  kafka:
    bootstrap-servers: ${KF_HOST}